class Constants:
    EXPERIMENTAL = True
    SHOW_VISUALIZERS = False

    HUB_CAMERA = 0 #FIXME
    HUB_TARGET_DIAMETER = 9000 #FIXME

    BALL_DETECTION_CAMERA_LEFT = 0 #FIXME
    BALL_DETECTION_CAMERA_RIGHT = 2 #FIXME
    BALL_DETECTION_BASELINE = 20 #FIXME

    CLIMBER_CAMERA = 0 #FIXME

    BOUNDING_COLOR = (0,255,0)

    USBCAMERA_ALPHA = 50 # TODO: Find horizonatl FOV
    USBCAMERA_BETA = 30 # TODO: Find vertical FOV

    # Module 1
    MODULE_1_CAMID = 0